<?php

namespace App\Livewire\Traits;

use Illuminate\Support\Facades\Log;
use Throwable;

trait HandlesPrefillLinks
{
    protected const PREFILL_URL_WARNING_LENGTH = 1800;

    /**
     * 事前入力モーダルの表示状態
     */
    public bool $showPrefillModal = false;

    /**
     * 生成された事前入力用URL
     */
    public string $generatedPrefillURL = '';

    /**
     * prefillパラメータを適用
     */
    protected function applyPrefillParams(): void
    {
        foreach ($this->prefillParams as $columnId => $value) {
            if (array_key_exists($columnId, $this->content)) {
                $column = $this->getColumnById((int) $columnId);

                $this->content[$columnId] = $this->normalizePrefillValueForContent($column, $value);
            }
        }
    }

    /**
     * 事前入力リンクを生成
     */
    public function generatePrefillLink(): void
    {
        $params = [];

        foreach ($this->content as $columnId => $value) {
            // 空の値はスキップ
            if ($this->isEmptyValue($value)) {
                continue;
            }

            $column = $this->getColumnById($columnId);
            if (! $column) {
                continue;
            }

            // auto_number と files は対象外
            if (in_array($column->type, ['auto_number', 'files'])) {
                continue;
            }

            // 自動生成カラムは初期値と異なる場合のみ含める
            if ($this->isAutoGeneratedColumn($column)) {
                $initialValue = $this->getInitialValue($column);
                if ($value === $initialValue) {
                    continue; // 初期値と同じなので含めない
                }
            }

            // パラメータに追加
            if (is_array($value)) {
                $filteredValue = $this->normalizeArrayValueForPrefillUrl($column, $value);
                if (! empty($filteredValue)) {
                    $params['prefill'][$columnId] = $filteredValue;
                }
            } else {
                $params['prefill'][$columnId] = $value;
            }
        }

        // URL生成
        $this->generatedPrefillURL = route('ledger.create', [
            'tenant' => $this->tenantId,
            'ledgerDefineId' => $this->ledgerDefineId,
        ]).'?'.http_build_query($params);

        $this->showPrefillModal = true;
    }

    /**
     * 値が空かどうかチェック
     */
    protected function isEmptyValue($value): bool
    {
        if (is_array($value)) {
            return $this->filterFilledArrayValues($value) === [];
        }

        if (is_bool($value)) {
            return $value === false;
        }

        return empty(trim((string) $value));
    }

    protected function normalizePrefillValueForContent(?object $column, mixed $value): mixed
    {
        if (! $column || $column->type !== 'chk') {
            return $value;
        }

        return $this->normalizeCheckboxSelections($column, $value);
    }

    protected function normalizeArrayValueForPrefillUrl(object $column, array $value): array
    {
        if ($column->type === 'chk') {
            return $this->normalizeCheckboxSelections($column, $value, returnBooleanMap: false);
        }

        return array_values($this->filterFilledArrayValues($value));
    }

    protected function normalizeCheckboxSelections(object $column, mixed $value, bool $returnBooleanMap = true): array
    {
        if (! is_array($value) && ! is_string($value)) {
            return [];
        }

        $validOptions = $column->options ?? [];
        $normalized = [];

        if (is_string($value)) {
            $option = $this->sanitizePrefillCheckboxOption($value);

            if ($option !== null && ($validOptions === [] || in_array($option, $validOptions, true))) {
                $normalized[$option] = $returnBooleanMap ? true : '1';
            }

            return $normalized;
        }

        if (array_is_list($value)) {
            foreach ($value as $option) {
                $sanitizedOption = $this->sanitizePrefillCheckboxOption($option);

                if ($sanitizedOption === null) {
                    continue;
                }

                if ($validOptions !== [] && ! in_array($sanitizedOption, $validOptions, true)) {
                    continue;
                }

                $normalized[$sanitizedOption] = $returnBooleanMap ? true : '1';
            }

            return $normalized;
        }

        foreach ($value as $option => $selected) {
            $sanitizedOption = $this->sanitizePrefillCheckboxOption($option);

            if ($sanitizedOption === null) {
                continue;
            }

            if ($validOptions !== [] && ! in_array($sanitizedOption, $validOptions, true)) {
                continue;
            }

            if (! $this->isTruthyPrefillCheckboxSelection($selected)) {
                continue;
            }

            $normalized[$sanitizedOption] = $returnBooleanMap ? true : '1';
        }

        return $normalized;
    }

    protected function sanitizePrefillCheckboxOption(mixed $option): ?string
    {
        if (! is_string($option)) {
            return null;
        }

        $sanitizedOption = trim(strip_tags(mb_substr($option, 0, 255)));

        return $sanitizedOption === '' ? null : $sanitizedOption;
    }

    protected function filterFilledArrayValues(array $value): array
    {
        return array_filter($value, function ($item) {
            if (is_array($item)) {
                return ! $this->isEmptyValue($item);
            }

            if (is_bool($item)) {
                return $item;
            }

            return trim((string) $item) !== '';
        });
    }

    protected function isTruthyPrefillCheckboxSelection(mixed $value): bool
    {
        if (is_bool($value)) {
            return $value;
        }

        if (is_int($value) || is_float($value)) {
            return (int) $value === 1;
        }

        if (! is_string($value)) {
            return false;
        }

        return in_array(strtolower(trim($value)), ['1', 'true', 'on', 'yes'], true);
    }

    /**
     * 自動生成カラムかどうか判定
     */
    protected function isAutoGeneratedColumn(object $column): bool
    {
        return in_array($column->type, ['user_name', 'YMD', 'YMDHM']);
    }

    /**
     * カラムの初期値を取得
     */
    public function getInitialValue(object $column)
    {
        return match ($column->type) {
            'user_name' => method_exists($column, 'getInputType')
                    && $column->getInputType() instanceof \App\Models\ColumnTypes\UserNameType
                ? $column->getInputType()->generateValue(
                    \Illuminate\Support\Facades\Auth::user()
                )
                : '',
            'YMD' => now()->format('Y-m-d'),
            'YMDHM' => now()->format('Y-m-d H:i'),
            default => '',
        };
    }

    /**
     * クリップボードにコピー（テスト用イベント発行）
     */
    public function copyPrefillLinkToClipboard(): void
    {
        $this->dispatch('copy-to-clipboard', text: $this->generatedPrefillURL);
    }

    /**
     * コピー成功通知（テスト用）
     */
    public function notifyCopySuccess(): void
    {
        $this->dispatch('prefill-copy-success');
    }

    /**
     * コピー失敗通知（テスト用）
     */
    public function notifyCopyFailed(): void
    {
        $this->dispatch('prefill-copy-failed');
    }

    /**
     * QRコード（SVG）を取得
     */
    public function getPrefillQRCodeProperty(): string
    {
        if (empty($this->generatedPrefillURL)) {
            return '';
        }

        try {
            return \SimpleSoftwareIO\QrCode\Facades\QrCode::size(200)
                ->margin(1)
                ->generate($this->generatedPrefillURL);
        } catch (Throwable $e) {
            Log::warning('Prefill QR code generation skipped.', [
                'ledger_define_id' => $this->ledgerDefineId ?? null,
                'tenant_id' => $this->tenantId ?? null,
                'prefill_url_length' => strlen($this->generatedPrefillURL),
                'exception' => $e::class,
                'message' => $e->getMessage(),
            ]);

            return '';
        }
    }

    public function getPrefillUrlLengthProperty(): int
    {
        return strlen($this->generatedPrefillURL);
    }

    public function getPrefillUrlIsLongProperty(): bool
    {
        return $this->prefillUrlLength >= self::PREFILL_URL_WARNING_LENGTH;
    }
}
