<?php

namespace App\Livewire\Traits;

trait HandlesPrefillLinks
{
    /**
     * 事前入力モーダルの表示状態
     */
    public bool $showPrefillModal = false;

    /**
     * 生成された事前入力用URL
     */
    public string $generatedPrefillURL = '';

    /**
     * prefillパラメータを適用
     */
    protected function applyPrefillParams(): void
    {
        foreach ($this->prefillParams as $columnId => $value) {
            if (array_key_exists($columnId, $this->content)) {
                $this->content[$columnId] = $value;
            }
        }
    }

    /**
     * 事前入力リンクを生成
     */
    public function generatePrefillLink(): void
    {
        $params = [];

        foreach ($this->content as $columnId => $value) {
            // 空の値はスキップ
            if ($this->isEmptyValue($value)) {
                continue;
            }

            $column = $this->getColumnById($columnId);
            if (! $column) {
                continue;
            }

            // auto_number と files は対象外
            if (in_array($column->type, ['auto_number', 'files'])) {
                continue;
            }

            // 自動生成カラムは初期値と異なる場合のみ含める
            if ($this->isAutoGeneratedColumn($column)) {
                $initialValue = $this->getInitialValue($column);
                if ($value === $initialValue) {
                    continue; // 初期値と同じなので含めない
                }
            }

            // パラメータに追加
            if (is_array($value)) {
                // 配列の場合、空要素を除去してから追加
                $filteredValue = array_filter($value, 'strlen');
                if (! empty($filteredValue)) {
                    $params['prefill'][$columnId] = array_values($filteredValue);
                }
            } else {
                $params['prefill'][$columnId] = $value;
            }
        }

        // URL生成
        $this->generatedPrefillURL = route('ledger.create', [
            'tenant' => $this->tenantId,
            'ledgerDefineId' => $this->ledgerDefineId,
        ]).'?'.http_build_query($params);

        $this->showPrefillModal = true;
    }

    /**
     * 値が空かどうかチェック
     */
    protected function isEmptyValue($value): bool
    {
        if (is_array($value)) {
            return empty(array_filter($value, 'strlen'));
        }

        return empty(trim((string) $value));
    }

    /**
     * 自動生成カラムかどうか判定
     */
    protected function isAutoGeneratedColumn(object $column): bool
    {
        return in_array($column->type, ['user_name', 'YMD', 'YMDHM']);
    }

    /**
     * カラムの初期値を取得
     */
    public function getInitialValue(object $column)
    {
        return match ($column->type) {
            'user_name' => method_exists($column, 'getInputType') && $column->getInputType() instanceof \App\Models\ColumnTypes\UserNameType
                ? $column->getInputType()->generateValue(\Illuminate\Support\Facades\Auth::user())
                : '',
            'YMD' => now()->format('Y-m-d'),
            'YMDHM' => now()->format('Y-m-d H:i'),
            default => '',
        };
    }

    /**
     * クリップボードにコピー（テスト用イベント発行）
     */
    public function copyPrefillLinkToClipboard(): void
    {
        $this->dispatch('copy-to-clipboard', text: $this->generatedPrefillURL);
    }

    /**
     * コピー成功通知（テスト用）
     */
    public function notifyCopySuccess(): void
    {
        $this->dispatch('prefill-copy-success');
    }

    /**
     * コピー失敗通知（テスト用）
     */
    public function notifyCopyFailed(): void
    {
        $this->dispatch('prefill-copy-failed');
    }

    /**
     * QRコード（SVG）を取得
     */
    public function getPrefillQRCodeProperty(): string
    {
        if (empty($this->generatedPrefillURL)) {
            return '';
        }

        return \SimpleSoftwareIO\QrCode\Facades\QrCode::size(200)
            ->margin(1)
            ->generate($this->generatedPrefillURL);
    }
}
