services:
  laravel:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      tika:
        condition: service_started
  queue:
    build:
      context: ./docker/app
      dockerfile: DockerfileQueue
      args:
        WWWGROUP: '${WWWGROUP}'
        DOCKER_GROUP_ID: '${DOCKER_GROUP_ID}'
    image: sail-8.4/app
    command: [ "php", "/var/www/html/artisan", "queue:work", "--tries=3" ]
    environment:
      WWWUSER: '${WWWUSER}'
      DOCKER_GROUP_ID: "${DOCKER_GROUP_ID}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      LOG_CHANNEL: 'queue'
    group_add:
      - '${DOCKER_GROUP_ID}'
    volumes:
      - '.:/var/www/html'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      tika:
        condition: service_started
    restart: on-failure

  # --- scheduler サービス ---
  scheduler:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    volumes:
      - .:/var/www/html
    command: [ "php", "/var/www/html/artisan", "schedule:work", "--no-interaction" ]
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      LOG_CHANNEL: 'scheduler'
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  mysql:
    image: 'groonga/mroonga:mysql-8.0-latest'
    platform: linux/amd64
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      - './docker/mroonga/my.cnf:/etc/mysql/conf.d/mroonga.cnf'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  redis:
      image: 'redis:alpine'
      ports:
          - '${FORWARD_REDIS_PORT:-6379}:6379'
      volumes:
          - 'sail-redis:/data'
      networks:
          - sail
      healthcheck:
          test:
              - CMD
              - redis-cli
              - ping
          retries: 3
          timeout: 5s
  tika:
    image: apache/tika:latest
    platform: linux/amd64
    ports:
      - 9998:9998
    #        command: -c /tika-config.xml
    restart: on-failure
    volumes:
      - './docker/tika/tika-config.xml:/tika-config.xml'
    networks:
      - sail
  ocrmypdf:
    build:
      context: ./docker/ocrmypdf
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/w
ww/html
    entrypoint: []
    command: tail -f /dev/null
    restart: unless-stopped
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
