<?php

return [
    // Path to the compiled manifest generated by Blade UI Icons (if used)
    'manifest_path' => env('BLADE_UI_ICONS_MANIFEST', resource_path('icons/manifest.json')),

    // Default sets (if required)
    'auto_discover' => true,

    // You can register custom icon sets here
    'sets' => [
        // 'heroicon' => [
        //     'path' => resource_path('icons/heroicon'),
        //     'prefix' => 'heroicon',
        //     'class' => '\\BladeUI\\Icons\\Svg\\SvgIcon',
        // ],
    ],
];
