<?php

namespace App\Filament\Resources;

use App\Filament\Resources\FolderResource\Pages;
use App\Filament\Resources\FolderResource\RelationManagers;
use App\Models\Folder;
use CodeWithDennis\FilamentSelectTree\SelectTree;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class FolderResource extends Resource
{
    public static bool $shouldRegisterNavigation = false;

    protected static ?string $model = Folder::class;

    protected static ?string $navigationIcon = 'heroicon-o-folder';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('title')
                    ->required()
                    ->maxLength(255),
                Forms\Components\Select::make('creator_id')
                    ->label('Creator')
                    ->relationship('creator', 'name')
                    ->searchable()
                    ->required(),
                Forms\Components\Select::make('modifier_id')
                    ->label('Modifier')
                    ->relationship('modifier', 'name')
                    ->searchable()
                    ->required(),
                SelectTree::make('parent_id')
                    ->label('Parent Folder')
                    ->relationship('parent', 'title', 'parent_id')
                    ->withCount()
//                    ->alwaysOpen()
                    ->defaultOpenLevel(10),
                Forms\Components\Select::make('roles')
                    ->relationship('roles', 'name')
                    ->multiple()
                    ->label('Roles')
                    ->required(),
                Forms\Components\Hidden::make('lft'),
                Forms\Components\Hidden::make('rgt'),
                Forms\Components\Hidden::make('lvl'),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('title')->sortable()->searchable(),
                Tables\Columns\TextColumn::make('creator.name')->label('Creator')->sortable()->searchable(),
                Tables\Columns\TextColumn::make('modifier.name')->label('Modifier')->sortable()->searchable(),
                Tables\Columns\TextColumn::make('parent.title')->label('Parent Folder')->sortable()->searchable(),
                Tables\Columns\TextColumn::make('roles.name')
                    ->label('Roles')
                    ->getStateUsing(function ($record) {
                        return $record->roles->pluck('name')->toArray();
                    })
                    ->badge(),
                Tables\Columns\TextColumn::make('created_at')->dateTime()->sortable(),
                Tables\Columns\TextColumn::make('updated_at')->dateTime()->sortable(),
                //                Tables\Columns\TextColumn::make('deleted_at')->dateTime()->sortable()->visible(fn ($record) => $record->trashed()),
            ])
            ->filters([
                Tables\Filters\TrashedFilter::make(),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\RestoreAction::make()->visible(fn($record) => $record->trashed()),
                Tables\Actions\DeleteAction::make(),
                Tables\Actions\ForceDeleteAction::make()->visible(fn($record) => $record->trashed()),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
                Tables\Actions\RestoreBulkAction::make(),
                Tables\Actions\ForceDeleteBulkAction::make(),
            ]);

    }

    public static function getRelations(): array
    {
        return [
            RelationManagers\ChildrenRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListFolders::route('/'),
            'create' => Pages\CreateFolder::route('/create'),
            'edit' => Pages\EditFolder::route('/{record}/edit'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->withoutGlobalScopes([
                SoftDeletingScope::class,
            ])
            ->with(['children', 'roles', 'ancestors.roles']);
    }

    public static function canViewAny(): bool
    {
        return true; // または適切な権限チェック
    }

    public static function canCreate(): bool
    {
        return true; // TODO: Change the autogenerated stub
    }

    public static function canEdit($record): bool
    {
        return true;
        //        return parent::canEdit($record); // TODO: Change the autogenerated stub
    }

    public static function canDelete($record): bool
    {
        return true;
        //        return parent::canDelete($record); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return true;

        return parent::canDeleteAny(); // TODO: Change the autogenerated stub
    }
}
