<?php

namespace App\Filament\Resources;

use App\Filament\Resources\TagResource\Pages;
use App\Filament\Resources\TagResource\RelationManagers\LedgerDefinesRelationManager;
use App\Models\Tag;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;

class TagResource extends Resource
{
    public static bool $shouldRegisterNavigation = false;

    protected static ?string $model = Tag::class;

    //    protected static \BackedEnum|string|null $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static \BackedEnum|string|null $navigationIcon = 'heroicon-o-tag';

    protected static ?string $navigationLabel = 'Tags';

    // オプション: ナビゲーションの順序を設定
    protected static ?int $navigationSort = 3; // 適切な数字に調整

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->maxLength(255),
                /*                Forms\Components\Select::make('roles')
                    ->multiple()
                    ->relationship('roles', 'name')
                    ->preload(),*/
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('ledger.tag.tag'))
                    ->sortable()
                    ->searchable(),
                //                Tables\Columns\TagsColumn::make('roles.name'),
                Tables\Columns\TextColumn::make('ledgerDefines')
                    ->label(__('ledger.title'))
                    ->badge()
                    ->getStateUsing(fn ($record) => $record->ledgerDefine()->pluck('title')),
                Tables\Columns\TextColumn::make('creator.name')->label(__('ledger.creator.name'))
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')->label(__('ledger.created_at'))
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                EditAction::make(),
                DeleteAction::make(),
            ])
            ->bulkActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ])
            ->defaultSort('name');
    }

    public static function getRelations(): array
    {
        return [
            LedgerDefinesRelationManager::class,
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListTags::route('/'),
            'create' => Pages\CreateTag::route('/create'),
            'edit' => Pages\EditTag::route('/{record}/edit'),
        ];
    }

    public static function canViewAny(): bool
    {
        return true; // または適切な権限チェック
    }

    public static function canCreate(): bool
    {
        return true; // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return true;
        //        return parent::canEdit($record); // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return true;
        //        return parent::canDelete($record); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return true;

        return parent::canDeleteAny(); // TODO: Change the autogenerated stub
    }
}
