<?php

namespace App\Filament\Resources;

use App\Filament\Resources\TagResource\Pages;
use App\Models\Tag;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;

class TagResource extends Resource
{
    public static bool $shouldRegisterNavigation = false;

    protected static ?string $model = Tag::class;

    //    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $navigationIcon = 'heroicon-o-tag';

    protected static ?string $navigationLabel = 'Tags';

    // オプション: ナビゲーションの順序を設定
    protected static ?int $navigationSort = 3; // 適切な数字に調整

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->maxLength(255),
                Forms\Components\Select::make('roles')
                    ->multiple()
                    ->relationship('roles', 'name')
                    ->preload(),
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name'),
                Tables\Columns\TagsColumn::make('roles.name'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListTags::route('/'),
            'create' => Pages\CreateTag::route('/create'),
            'edit' => Pages\EditTag::route('/{record}/edit'),
        ];
    }

    public static function canViewAny(): bool
    {
        return true; // または適切な権限チェック
    }

    public static function canCreate(): bool
    {
        return true; // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return true;
        //        return parent::canEdit($record); // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return true;
        //        return parent::canDelete($record); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return true;

        return parent::canDeleteAny(); // TODO: Change the autogenerated stub
    }
}
