name: Laravel Sail with Mroonga Debug

on:
  push:
  pull_request:

env:
  DB_USERNAME: sail
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  MAIL_FROM_ADDRESS: info@example.com
  DB_PORT: 3306
  DB_DATABASE: laravel

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: groonga/mroonga:mysql-8.0-latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ledgerleap
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, pdo_mysql
          tools: composer:v2

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --quiet --prefer-dist --no-progress --no-interaction --no-scripts --no-ansi
      - name: Laravel Setting
        run: |
          cp .env.example .env
          php artisan optimize
          git config --local core.fileMode false
          chmod -R 777 storage bootstrap/cache
      - name: PHP Version
        run: php --version
      - name: Composer Version
        run: composer --version
      - name: Laravel Version
        run: php artisan --version
      - name: Composer Validate
        run: composer validate
      - name: Run Migrate
        run: php artisan migrate
      - name: Run Migrate Refresh
        run: php artisan migrate:refresh
      - name: Run Seeding
        run: php artisan db:seed
      - name: Run IDE Helper Models
        run: |
          php artisan ide-helper:models --write --reset
          ./vendor/bin/pint app/Models
          if ! git diff --exit-code; then
            echo "Error: The phpdoc for the model ide-helper is not updated!"
            echo "Run: php artisan ide-helper:models --write --reset"
            exit 1
          fi
      - name: Cache Pint
        uses: actions/cache@v4
        with:
          path: ./.pint.cache
          key: ${{ runner.os }}-pint-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-pint-
      - name: Run Pint
        run: ./vendor/bin/pint --test
      - name: Cache Rector
        uses: actions/cache@v4
        with:
          path: ./storage/rector/cache
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-rector-
      - name: Run Rector
        run: ./vendor/bin/rector process --dry-run
      - name: Cache PHPStan
        uses: actions/cache@v4
        with:
          path: ./storage/phpstan
          key: ${{ runner.os }}-phpstan-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-phpstan-
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze
      - name: Cache Pest
        uses: actions/cache@v4
        with:
          path: ./storage/pest/cache
          key: ${{ runner.os }}-pest-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-pest-
      - name: Run Pest
        env:
          SESSION_DRIVER: array
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: ./vendor/bin/pest --parallel --cache-directory storage/pest/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        if: always()
        run: vendor/bin/phpunit

      - name: Check PHP Version and Configuration
        continue-on-error: true
        run: |
          php -v
          php -n -i | grep "Loaded Configuration File" # -n オプションを追加
          php -n -i | grep "variables_order"
          php -n -i | grep "register_globals"
          php -i | grep extension_dir # extension_dir を確認

      - name: Check .env Content
        run: cat .env

      - name: Check PHP Environment Variables (Crucial Debug)
        continue-on-error: true
        run: |
          php -r "var_dump(getenv('DB_HOST')); var_dump(getenv('DB_DATABASE')); var_dump(getenv('APP_ENV'));"
          php -r "print_r($_ENV);"
          php -r "print_r($_SERVER);"

      - name: Check Composer Autoload
        run: |
          COMPOSER_BIN=$(which composer)
          if [ -n "$COMPOSER_BIN" ]; then
              echo "Composer found: $COMPOSER_BIN"
              ls -l vendor/autoload.php
          else
              echo "Composer not found"
          fi
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate --env testing

      - name: Set hostname
        run: sudo echo "127.0.0.1 mysql" | sudo tee -a /etc/hosts

      - name: Grant database privileges
        env:
          MYSQL_PWD: ${{ secrets.DB_PASSWORD }}
        run: |
          mysql -h mysql -u root --force <<EOF
            GRANT ALL PRIVILEGES ON ledgerleap.* TO '${{ env.DB_USERNAME }}'@'%';
            FLUSH PRIVILEGES;
            CREATE DATABASE IF NOT EXISTS ledgerleap;
          EOF

      - name: Clear Config Cache
        run: php artisan config:clear

      - name: ディレクトリ構造の確認
        run: ls -lR ${{ github.workspace }}
