name: Laravel

on:
  push:
  pull_request:

env:
  DB_USERNAME: sail
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  MAIL_FROM_ADDRESS: info@example.com

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql.test:
        image: 'groonga/mroonga:mysql-8.0-latest'
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: 'ledgerleap'
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, pdo_mysql
          tools: composer:v2
      - name: Copy .env.example to .env.testing
        run: cp .env.example .env.testing
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate --env testing
      - name: Set hostname
        run: sudo echo "127.0.0.1 mysql.test" | sudo tee -a /etc/hosts
      - name: Grant database privileges
        env:
          MYSQL_PWD: ${{ secrets.DB_PASSWORD }}
        run: |
          mysql -h mysql.test -u root --force <<EOF
            GRANT ALL PRIVILEGES ON ledgerleap.* TO '${{ env.DB_USERNAME }}'@'%';
            FLUSH PRIVILEGES;
            CREATE DATABASE IF NOT EXISTS ledgerleap;
          EOF
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: ${{ github.workspace }} # 重要
        run: vendor/bin/phpunit
      - name: ディレクトリ構造の確認 # デバッグ用
        run: ls -lR ${{ github.workspace }}
      - name: 環境変数の確認 # デバッグ用
        run: |
          echo "APP_ENV: $APP_ENV"
          echo "DB_DATABASE: $DB_DATABASE"
          cat .env.testing

